[formatter.end-of-file-fixer]
command = "end-of-file-fixer"
includes = ["*.py", "*.toml", "*.nix", "*.md", "*.json", "*.yml", "*.yaml", "*.lock", ".gitignore", ".envrc"]

[formatter.trailing-whitespace-fixer]
command = "trailing-whitespace-fixer"
includes = ["*.py", "*.toml", "*.nix", "*.md", "*.json", "*.yml", "*.yaml"]

[formatter.ruff]
command = "ruff"
options = ["format"]
includes = ["*.py"]

[formatter.ruff-check]
command = "ruff"
options = ["check", "--fix"]
includes = ["*.py"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write", "--prose-wrap", "always"]
includes = ["*.md", "*.json", "*.yml", "*.yaml"]
